 javax.persistence.jdbc.url=jdbc:mysql://localhost:3306/myhibernate
 javax.persistence.jdbc.user=root
 javax.persistence.jdbc.password=Kumar@123
 javax.persistence.jdbc.driver=com.mysql.cj.jdbc.Driver 
 hibernate.hbm2ddl.auto=update
 hibernate.dialect=org.hibernate.dialect.MySQL8Dialect 
 hibernate.show_sql=true